mutation ContactAddressUpdate($cartId : ID!,
    $delivery : CartDeliveryAddressInput!,
    $id : ID!,
    $buyerIdentity : CartBuyerIdentityInput!,
    $create : Boolean = false,
    $updateBuyer : Boolean = true,
){
    cartBuyerIdentityUpdate(cartId: $cartId,
        buyerIdentity:$buyerIdentity) @include(if: $updateBuyer){
        userErrors {
            code
            field
            message
        }
        warnings {
            code
            message
            target
        }
    }
    cartDeliveryAddressesUpdate (cartId: $cartId,addresses: [{
        id: $id
        selected: true
        address: {
            deliveryAddress: $delivery
        }
    }]) @skip(if: $create){
        cart {
            ...CartFields
        }
        userErrors {
            code
            field
            message
        }
        warnings {
            code
            message
            target
        }
    }

    cartDeliveryAddressesAdd(cartId: $cartId,addresses: [{
        selected: true
        address: {
            deliveryAddress: $delivery
        }
    }]) @include(if: $create){
        cart {
            ...CartFields
        }
        userErrors {
            code
            field
            message
        }
        warnings {
            code
            message
            target
        }
    }
}
