mutation Discount($cartId : ID!,$codes : [String!]){
    cartDiscountCodesUpdate(cartId: $cartId,discountCodes: $codes){
        cart {
            ...Discounts
        }
        userErrors {
            ...Errors
        }
        warnings {
            code
            message
            target
        }
    }
}
