fragment CartFields on Cart{
    id
    ...BuyerIdentity
    totalQuantity
    discountCodes {
        code
        applicable
    }
    ...Delivery
    cost {
        checkoutChargeAmount {
            amount
            currencyCode
        }
        subtotalAmount {
            amount
            currencyCode
        }
        subtotalAmountEstimated
        totalAmount {
            currencyCode
            amount
        }
        totalAmountEstimated
    }
}
