fragment CartFields on Cart{
    id
    ...BuyerIdentity
    totalQuantity
    discountCodes {
        code
        applicable
    }
    ...Delivery
    discountAllocations {
        ... on CartCodeDiscountAllocation{
            code
        }
        ... on CartCustomDiscountAllocation{
            title
        }
        ... on CartAutomaticDiscountAllocation{
            title
        }
        targetType
        __typename
        discountedAmount {
            __typename
            amount
            currencyCode
        }
        discountApplication {
            __typename
            allocationMethod
            targetSelection
            targetType
            value {
                ... on MoneyV2{
                    currencyCode
                    amount
                }
            }
        }
    }
    cost {
        checkoutChargeAmount {
            amount
            currencyCode
        }
        subtotalAmount {
            amount
            currencyCode
        }
        subtotalAmountEstimated
        totalAmount {
            currencyCode
            amount
        }
        totalAmountEstimated
    }
}
