fragment Delivery on Cart{
    delivery {
        addresses(selected: true){
            id
            selected
            oneTimeUse
            __typename
            address {
                ... on CartDeliveryAddress{
                    firstName
                    lastName
                    name
                    address1
                    address2
                    phone
                    city
                    countryCode
                    provinceCode
                    formatted
                    formattedArea
                    zip
                }
            }
        }
    }
}
